define(["exports", "module", "@beyond-js/kernel/bundle", "@beyond-js/widgets/render", "@beyond-js/kernel/styles", "svelte@3.48.0/internal", "@beyond-js/svelte-widgets/base", "@beyond/docs/examples-sm-actions"], function (_exports, _amd_module, dependency_0, dependency_1, dependency_2, dependency_3, dependency_4, dependency_5) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.hmr = _exports.Controller = void 0;
  const __url = _amd_module.uri;
  const {
    Bundle: __Bundle,
    externals
  } = dependency_0;

  const __pkg = new __Bundle({
    "module": "@beyond/docs/examples/sm/counter-svelte",
    "bundle": "widget"
  }, __url).package();

  ;
  externals.register(new Map([["svelte/internal", dependency_3]]));

  __pkg.dependencies.update(new Set(["@beyond/docs/examples-sm-actions"]));

  brequire('@beyond-js/widgets/render').widgets.register([{
    "name": "counter-svelte",
    "id": "@beyond/docs/examples/sm/counter-svelte"
  }]);
  brequire('@beyond-js/kernel/styles').styles.register('@beyond/docs/examples/sm/counter-svelte');
  const ims = new Map();
  /*******************************
  INTERNAL MODULE: ./widget.svelte
  *******************************/

  ims.set('./widget.svelte', {
    hash: 2163876209,
    creator: function (require, exports) {
      "use strict";

      Object.defineProperty(exports, "__esModule", {
        value: true
      });
      exports.default = void 0;

      var _internal = require("svelte/internal");

      var _examplesSmActions = require("@beyond/docs/examples-sm-actions");
      /* generated by Svelte v3.49.0 */


      function create_fragment(ctx) {
        let div1;
        let div0;
        let h3;
        let t1;
        let span;
        let t2;
        let t3;
        let mounted;
        let dispose;
        return {
          c() {
            div1 = (0, _internal.element)("div");
            div0 = (0, _internal.element)("div");
            h3 = (0, _internal.element)("h3");
            h3.textContent = "Svelte Panel";
            t1 = (0, _internal.space)();
            span = (0, _internal.element)("span");
            t2 = (0, _internal.text)("clicks here: ");
            t3 = (0, _internal.text)(
            /*count*/
            ctx[0]);
            (0, _internal.attr)(div0, "class", "item svelte-1qghxe7");
            (0, _internal.attr)(div1, "class", "list");
          },

          m(target, anchor) {
            (0, _internal.insert)(target, div1, anchor);
            (0, _internal.append)(div1, div0);
            (0, _internal.append)(div0, h3);
            (0, _internal.append)(div0, t1);
            (0, _internal.append)(div0, span);
            (0, _internal.append)(span, t2);
            (0, _internal.append)(span, t3);

            if (!mounted) {
              dispose = (0, _internal.listen)(div0, "click",
              /*add*/
              ctx[1]);
              mounted = true;
            }
          },

          p(ctx, [dirty]) {
            if (dirty &
            /*count*/
            1) (0, _internal.set_data)(t3,
            /*count*/
            ctx[0]);
          },

          i: _internal.noop,
          o: _internal.noop,

          d(detaching) {
            if (detaching) (0, _internal.detach)(div1);
            mounted = false;
            dispose();
          }

        };
      }

      function instance($$self, $$props, $$invalidate) {
        let count = 0;

        const add = () => {
          $$invalidate(0, ++count);
          (0, _examplesSmActions.updateCount)();
        };

        return [count, add];
      }

      class Component extends _internal.SvelteComponent {
        constructor(options) {
          super();
          (0, _internal.init)(this, options, instance, create_fragment, _internal.safe_not_equal, {});
        }

      }

      var _default = Component;
      exports.default = _default;
    }
  });
  /****************************
  INTERNAL MODULE: ./controller
  ****************************/

  ims.set('./controller', {
    hash: 1882192267,
    creator: function (require, exports) {
      "use strict";

      Object.defineProperty(exports, "__esModule", {
        value: true
      });
      exports.Controller = void 0;

      var _base = require("@beyond-js/svelte-widgets/base");

      var _widget = require("./widget.svelte");
      /*bundle*/


      class Controller extends _base.SvelteWidgetController {
        get Widget() {
          return _widget.default;
        }

      }

      exports.Controller = Controller;
    }
  });
  __pkg.exports.descriptor = [{
    "im": "./controller",
    "from": "Controller",
    "name": "Controller"
  }];
  let Controller; // Module exports

  _exports.Controller = Controller;

  __pkg.exports.process = function ({
    require,
    prop,
    value
  }) {
    (require || prop === 'Controller') && (_exports.Controller = Controller = require ? require('./controller').Controller : value);
  };

  const hmr = new function () {
    this.on = (event, listener) => __pkg.hmr.on(event, listener);

    this.off = (event, listener) => __pkg.hmr.off(event, listener);
  }();
  _exports.hmr = hmr;

  __pkg.initialise(ims);
});
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxQ0FjYzs7O1lBQWNBLEdBQUs7Ozs7OztZQUxqQyxzQkFPTUMsTUFQTixFQU9NQyxJQVBOLEVBT01DLE1BUE47WUFDSSxzQkFLTUQsSUFMTixFQUtNRSxJQUxOO1lBQ0ksc0JBRUtBLElBRkwsRUFFS0MsRUFGTDs7WUFHQSxzQkFBaUNELElBQWpDLEVBQWlDRSxJQUFqQzs7Ozs7OztjQUp3Qk4sR0FBRzs7Ozs7Ozs7OztZQUlQQSxHQUFLOzs7Ozs7Ozs7Ozs7Ozs7O1lBYjdCTyxLQUFLLEdBQUc7O2NBQ05DLEdBQUc7NEJBQ0hEO1VBQ0Y7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O01DSko7O01BRUE7TUFFTzs7O01BQVUsTUFDWEUsVUFEVyxTQUNRQyw0QkFEUixDQUM4QjtRQUNqQyxJQUFOQyxNQUFNO1VBQ04sT0FBT0EsZUFBUDtRQUNIOztNQUgwQyIsIm5hbWVzIjpbImN0eCIsInRhcmdldCIsImRpdjEiLCJhbmNob3IiLCJkaXYwIiwiaDMiLCJzcGFuIiwiY291bnQiLCJhZGQiLCJDb250cm9sbGVyIiwiU3ZlbHRlV2lkZ2V0Q29udHJvbGxlciIsIldpZGdldCJdLCJzb3VyY2VSb290IjoiLyIsInNvdXJjZXMiOlsiZG9jdW1lbnRhdGlvbi9tb2R1bGVzL2V4YW1wbGVzL2NvdW50ZXIvY29tcG9uZW50cy9zdmVsdGUvd2lkZ2V0L3N2ZWx0ZSIsImRvY3VtZW50YXRpb24vbW9kdWxlcy9leGFtcGxlcy9jb3VudGVyL2NvbXBvbmVudHMvc3ZlbHRlL3dpZGdldC9zdmVsdGUvY29udHJvbGxlci50cyJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PmltcG9ydCB7IHVwZGF0ZUNvdW50IH0gZnJvbSBcIkBiZXlvbmQvZG9jcy9leGFtcGxlcy1zbS1hY3Rpb25zXCI7XHJcbmxldCBjb3VudCA9IDA7XHJcbmNvbnN0IGFkZCA9ICgpID0+IHtcclxuICAgICsrY291bnQ7XHJcbiAgICB1cGRhdGVDb3VudCgpO1xyXG59O1xyXG4vLyBleHBvcnQgZGVmYXVsdCBDb21wb25lbnQ7XHJcbjwvc2NyaXB0PlxyXG5cclxuPGRpdiBjbGFzcz1cImxpc3RcIj5cclxuICAgIDxkaXYgY2xhc3M9XCJpdGVtXCIgb246Y2xpY2s9e2FkZH0+XHJcbiAgICAgICAgPGgzPlxyXG4gICAgICAgICAgICBTdmVsdGUgUGFuZWxcclxuICAgICAgICA8L2gzPlxyXG4gICAgICAgIDxzcGFuPmNsaWNrcyBoZXJlOiB7Y291bnR9PC9zcGFuPlxyXG4gICAgPC9kaXY+XHJcbjwvZGl2PlxyXG5cclxuPHN0eWxlIGxhbmc9XCJzY3NzXCI+Lml0ZW0ge1xuICBwYWRkaW5nOiAxcmVtIDJyZW07XG4gIGN1cnNvcjogcG9pbnRlcjtcbiAgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tc2Vjb25kYXJ5LWRhcmspO1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLml0ZW06aG92ZXIsIC5pdGVtLnNlbGVjdGVkIHtcbiAgYmFja2dyb3VuZDogcmdiYSgyNTUsIDAsIDAsIDAuMyk7XG59PC9zdHlsZT5cclxuIixudWxsXX0=